In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df_1 = pd.read_csv("../data/historical/air_quality/air_quality_year_2023.csv")
df_2 = pd.read_csv("../data/historical/air_quality/air_quality_year_2024.csv")
df_3 = pd.read_csv("../data/historical/air_quality/air_quality_year_2025.csv")
df_aqi = pd.concat([df_1, df_2, df_3], axis=0, ignore_index=True)
df_aqi.head()

,location_id,location_name,date,pm10,pm2_5,carbon_monoxide,sulphur_dioxide,ozone,nitrogen_dioxide,aerosol_optical_depth,dust,us_aqi_pm2_5,us_aqi_pm10,us_aqi_nitrogen_dioxide,us_aqi_carbon_monoxide,us_aqi_ozone,us_aqi_sulphur_dioxide,us_aqi
0,1566083,Ho Chi Minh City,2023-01-01 00:00:00,95.0,65.0,993.0,37.50,25.0,84.40,0.29,0.0,133.11458,58.687496,41.568165,9.687199,24.002783,20.447111,133.11458
1,1566083,Ho Chi Minh City,2023-01-01 01:00:00,86.1,59.0,846.0,30.75,28.0,70.25,0.25,0.0,132.65625,58.570840,34.599094,10.109903,18.784786,16.766632,132.65625
2,1566083,Ho Chi Minh City,2023-01-01 02:00:00,83.4,57.0,821.0,28.90,26.0,65.80,0.24,0.0,131.73958,58.312500,32.407406,10.200483,14.784323,15.757906,131.73958
3,1566083,Ho Chi Minh City,2023-01-01 03:00:00,80.1,54.8,834.0,28.45,22.0,63.95,0.24,0.0,130.64583,58.002083,31.496256,10.055555,12.117347,15.512541,130.64583
4,1566083,Ho Chi Minh City,2023-01-01 04:00:00,69.4,47.5,838.0,27.20,20.0,60.10,0.23,0.0,129.43752,57.658333,29.600079,9.801933,11.421614,14.830973,129.43752

In [3]:
df_aqi.info()

<class 'pandas.DataFrame'>
RangeIndex: 263040 entries, 0 to 263039
Data columns (total 18 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   location_id              263040 non-null  int64
 1   location_name            263040 non-null  str
 2   date                     263040 non-null  str
 3   pm10                     263040 non-null  float64
 4   pm2_5                    263040 non-null  float64
 5   carbon_monoxide          263040 non-null  float64
 6   sulphur_dioxide          263040 non-null  float64
 7   ozone                    263040 non-null  float64
 8   nitrogen_dioxide         263040 non-null  float64
 9   aerosol_optical_depth    263040 non-null  float64
 10  dust                     263040 non-null  float64
 11  us_aqi_pm2_5             263040 non-null  float64
 12  us_aqi_pm10              263040 non-null  float64
 13  us_aqi_nitrogen_dioxide  263040 non-null  float64
 14  us_aqi_carbon_monoxide   263040 non-null  float64
 15  us_aqi_ozone             263040 non-null  float64
 16  us_aqi_sulphur_dioxide   263040 non-null  float64
 17  us_aqi                   263040 non-null  float64
dtypes: float64(15), int64(1), str(2)
memory usage: 43.5 MB

In [4]:
df_1 = pd.read_csv("../data/historical/weather/weather_year_2023.csv")
df_2 = pd.read_csv("../data/historical/weather/weather_year_2024.csv")
df_3 = pd.read_csv("../data/historical/weather/weather_year_2025.csv")
df_weather = pd.concat([df_1, df_2, df_3], axis=0, ignore_index=True)
df_weather.head()

,location_id,location_name,date,temperature_2m,relative_humidity_2m,rain,surface_pressure,cloud_cover,wind_speed_10m,wind_direction_10m,weather_code,sunshine_duration,boundary_layer_height,dew_point_2m,is_day
0,1566083,Ho Chi Minh City,2023-01-01 00:00:00,23.85,61.484700,0.0,1013.40027,100.0,11.304229,9.162280,3.0,0.0,70.0,16.0,0.0
1,1566083,Ho Chi Minh City,2023-01-01 01:00:00,23.30,62.749770,0.0,1013.19920,100.0,10.739833,13.570457,3.0,0.0,80.0,15.8,0.0
2,1566083,Ho Chi Minh City,2023-01-01 02:00:00,22.75,64.459640,0.0,1012.69824,100.0,8.287822,2.489499,3.0,0.0,105.0,15.7,0.0
3,1566083,Ho Chi Minh City,2023-01-01 03:00:00,22.25,65.602090,0.0,1012.29730,100.0,8.669949,4.763556,3.0,0.0,135.0,15.5,0.0
4,1566083,Ho Chi Minh City,2023-01-01 04:00:00,21.95,66.812325,0.0,1012.19680,100.0,7.928178,357.397500,3.0,0.0,145.0,15.5,0.0

In [5]:
df_weather.info()

<class 'pandas.DataFrame'>
RangeIndex: 263040 entries, 0 to 263039
Data columns (total 15 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   location_id            263040 non-null  int64
 1   location_name          263040 non-null  str
 2   date                   263040 non-null  str
 3   temperature_2m         263040 non-null  float64
 4   relative_humidity_2m   263040 non-null  float64
 5   rain                   263040 non-null  float64
 6   surface_pressure       263040 non-null  float64
 7   cloud_cover            263040 non-null  float64
 8   wind_speed_10m         263040 non-null  float64
 9   wind_direction_10m     263040 non-null  float64
 10  weather_code           263040 non-null  float64
 11  sunshine_duration      263040 non-null  float64
 12  boundary_layer_height  219360 non-null  float64
 13  dew_point_2m           263040 non-null  float64
 14  is_day                 263040 non-null  float64
dtypes: float64(12), int64(1), str(2)
memory usage: 37.5 MB

In [6]:
df = pd.merge(
    df_aqi, df_weather, on=["date", "location_id", "location_name"], how="inner"
)

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 263040 entries, 0 to 263039
Data columns (total 30 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   location_id              263040 non-null  int64
 1   location_name            263040 non-null  str
 2   date                     263040 non-null  str
 3   pm10                     263040 non-null  float64
 4   pm2_5                    263040 non-null  float64
 5   carbon_monoxide          263040 non-null  float64
 6   sulphur_dioxide          263040 non-null  float64
 7   ozone                    263040 non-null  float64
 8   nitrogen_dioxide         263040 non-null  float64
 9   aerosol_optical_depth    263040 non-null  float64
 10  dust                     263040 non-null  float64
 11  us_aqi_pm2_5             263040 non-null  float64
 12  us_aqi_pm10              263040 non-null  float64
 13  us_aqi_nitrogen_dioxide  263040 non-null  float64
 14  us_aqi_carbon_monoxide   263040 non-null  float64
 15  us_aqi_ozone             263040 non-null  float64
 16  us_aqi_sulphur_dioxide   263040 non-null  float64
 17  us_aqi                   263040 non-null  float64
 18  temperature_2m           263040 non-null  float64
 19  relative_humidity_2m     263040 non-null  float64
 20  rain                     263040 non-null  float64
 21  surface_pressure         263040 non-null  float64
 22  cloud_cover              263040 non-null  float64
 23  wind_speed_10m           263040 non-null  float64
 24  wind_direction_10m       263040 non-null  float64
 25  weather_code             263040 non-null  float64
 26  sunshine_duration        263040 non-null  float64
 27  boundary_layer_height    219360 non-null  float64
 28  dew_point_2m             263040 non-null  float64
 29  is_day                   263040 non-null  float64
dtypes: float64(27), int64(1), str(2)
memory usage: 67.6 MB

In [8]:
df.head()

,location_id,location_name,date,pm10,pm2_5,carbon_monoxide,sulphur_dioxide,ozone,nitrogen_dioxide,aerosol_optical_depth,...,rain,surface_pressure,cloud_cover,wind_speed_10m,wind_direction_10m,weather_code,sunshine_duration,boundary_layer_height,dew_point_2m,is_day
0,1566083,Ho Chi Minh City,2023-01-01 00:00:00,95.0,65.0,993.0,37.50,25.0,84.40,0.29,...,0.0,1013.40027,100.0,11.304229,9.162280,3.0,0.0,70.0,16.0,0.0
1,1566083,Ho Chi Minh City,2023-01-01 01:00:00,86.1,59.0,846.0,30.75,28.0,70.25,0.25,...,0.0,1013.19920,100.0,10.739833,13.570457,3.0,0.0,80.0,15.8,0.0
2,1566083,Ho Chi Minh City,2023-01-01 02:00:00,83.4,57.0,821.0,28.90,26.0,65.80,0.24,...,0.0,1012.69824,100.0,8.287822,2.489499,3.0,0.0,105.0,15.7,0.0
3,1566083,Ho Chi Minh City,2023-01-01 03:00:00,80.1,54.8,834.0,28.45,22.0,63.95,0.24,...,0.0,1012.29730,100.0,8.669949,4.763556,3.0,0.0,135.0,15.5,0.0
4,1566083,Ho Chi Minh City,2023-01-01 04:00:00,69.4,47.5,838.0,27.20,20.0,60.10,0.23,...,0.0,1012.19680,100.0,7.928178,357.397500,3.0,0.0,145.0,15.5,0.0

In [9]:
df.to_csv(
    "../data/clean/data.csv",
    index=False,
)