In [1]:
import pandas as pd

In [2]:
dfs = [
    pd.read_csv(f"../data/historical/air_quality/air_quality_year_{year}.csv")
    for year in range(2020, 2027)
]
df_aqi = pd.concat(dfs, axis=0, ignore_index=True)
df_aqi.head()

,location_id,location_name,date,pm10,pm2_5,carbon_monoxide,sulphur_dioxide,ozone,nitrogen_dioxide,aerosol_optical_depth,dust,us_aqi_pm2_5,us_aqi_pm10,us_aqi_nitrogen_dioxide,us_aqi_carbon_monoxide,us_aqi_ozone,us_aqi_sulphur_dioxide,us_aqi
0,1566083,Ho Chi Minh City,2020-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1566083,Ho Chi Minh City,2020-01-01 01:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1566083,Ho Chi Minh City,2020-01-01 02:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1566083,Ho Chi Minh City,2020-01-01 03:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1566083,Ho Chi Minh City,2020-01-01 04:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df_aqi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 517680 entries, 0 to 517679
Data columns (total 18 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   location_id              517680 non-null  int64
 1   location_name            517680 non-null  object
 2   date                     517680 non-null  object
 3   pm10                     290570 non-null  float64
 4   pm2_5                    290570 non-null  float64
 5   carbon_monoxide          290570 non-null  float64
 6   sulphur_dioxide          290570 non-null  float64
 7   ozone                    290570 non-null  float64
 8   nitrogen_dioxide         290570 non-null  float64
 9   aerosol_optical_depth    290570 non-null  float64
 10  dust                     290570 non-null  float64
 11  us_aqi_pm2_5             290330 non-null  float64
 12  us_aqi_pm10              290330 non-null  float64
 13  us_aqi_nitrogen_dioxide  290570 non-null  float64
 14  us_aqi_carbon_monoxide   290490 non-null  float64
 15  us_aqi_ozone             290480 non-null  float64
 16  us_aqi_sulphur_dioxide   290570 non-null  float64
 17  us_aqi                   290330 non-null  float64
dtypes: float64(15), int64(1), object(2)
memory usage: 71.1+ MB

---

In [4]:
dfs = [
    pd.read_csv(f"../data/historical/weather/weather_year_{year}.csv")
    for year in range(2020, 2027)
]
df_weather = pd.concat(dfs, axis=0, ignore_index=True)
df_weather.head()

,location_id,location_name,date,temperature_2m,relative_humidity_2m,rain,surface_pressure,cloud_cover,wind_speed_10m,wind_direction_10m,weather_code,sunshine_duration,boundary_layer_height,dew_point_2m,is_day
0,1566083,Ho Chi Minh City,2020-01-01 00:00:00,26.45,57.924744,0.0,1014.40564,84.0,10.966713,23.198618,3.0,0.0,160.0,17.50,0.0
1,1566083,Ho Chi Minh City,2020-01-01 01:00:00,25.60,57.904760,0.0,1013.90420,89.0,10.245780,18.435053,3.0,0.0,130.0,16.70,0.0
2,1566083,Ho Chi Minh City,2020-01-01 02:00:00,24.85,58.279884,0.0,1013.50275,88.0,10.245780,18.435053,3.0,0.0,145.0,16.10,0.0
3,1566083,Ho Chi Minh City,2020-01-01 03:00:00,24.15,62.143390,0.0,1012.90130,52.0,10.931203,17.241547,2.0,0.0,175.0,16.45,0.0
4,1566083,Ho Chi Minh City,2020-01-01 04:00:00,23.70,66.115654,0.0,1012.70056,82.0,10.966713,23.198618,3.0,0.0,190.0,17.00,0.0

In [5]:
df_weather.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 575520 entries, 0 to 575519
Data columns (total 15 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   location_id            575520 non-null  int64
 1   location_name          575520 non-null  object
 2   date                   575520 non-null  object
 3   temperature_2m         575520 non-null  float64
 4   relative_humidity_2m   575520 non-null  float64
 5   rain                   575520 non-null  float64
 6   surface_pressure       575520 non-null  float64
 7   cloud_cover            575520 non-null  float64
 8   wind_speed_10m         575520 non-null  float64
 9   wind_direction_10m     575520 non-null  float64
 10  weather_code           575520 non-null  float64
 11  sunshine_duration      575520 non-null  float64
 12  boundary_layer_height  531840 non-null  float64
 13  dew_point_2m           575520 non-null  float64
 14  is_day                 575520 non-null  float64
dtypes: float64(12), int64(1), object(2)
memory usage: 65.9+ MB

In [6]:
df = pd.merge(
    df_aqi, df_weather, on=["date", "location_id", "location_name"], how="inner"
)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 517680 entries, 0 to 517679
Data columns (total 30 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   location_id              517680 non-null  int64
 1   location_name            517680 non-null  object
 2   date                     517680 non-null  object
 3   pm10                     290570 non-null  float64
 4   pm2_5                    290570 non-null  float64
 5   carbon_monoxide          290570 non-null  float64
 6   sulphur_dioxide          290570 non-null  float64
 7   ozone                    290570 non-null  float64
 8   nitrogen_dioxide         290570 non-null  float64
 9   aerosol_optical_depth    290570 non-null  float64
 10  dust                     290570 non-null  float64
 11  us_aqi_pm2_5             290330 non-null  float64
 12  us_aqi_pm10              290330 non-null  float64
 13  us_aqi_nitrogen_dioxide  290570 non-null  float64
 14  us_aqi_carbon_monoxide   290490 non-null  float64
 15  us_aqi_ozone             290480 non-null  float64
 16  us_aqi_sulphur_dioxide   290570 non-null  float64
 17  us_aqi                   290330 non-null  float64
 18  temperature_2m           517680 non-null  float64
 19  relative_humidity_2m     517680 non-null  float64
 20  rain                     517680 non-null  float64
 21  surface_pressure         517680 non-null  float64
 22  cloud_cover              517680 non-null  float64
 23  wind_speed_10m           517680 non-null  float64
 24  wind_direction_10m       517680 non-null  float64
 25  weather_code             517680 non-null  float64
 26  sunshine_duration        517680 non-null  float64
 27  boundary_layer_height    474000 non-null  float64
 28  dew_point_2m             517680 non-null  float64
 29  is_day                   517680 non-null  float64
dtypes: float64(27), int64(1), object(2)
memory usage: 118.5+ MB

In [8]:
df.head()

,location_id,location_name,date,pm10,pm2_5,carbon_monoxide,sulphur_dioxide,ozone,nitrogen_dioxide,aerosol_optical_depth,...,rain,surface_pressure,cloud_cover,wind_speed_10m,wind_direction_10m,weather_code,sunshine_duration,boundary_layer_height,dew_point_2m,is_day
0,1566083,Ho Chi Minh City,2020-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,1014.40564,84.0,10.966713,23.198618,3.0,0.0,160.0,17.50,0.0
1,1566083,Ho Chi Minh City,2020-01-01 01:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,1013.90420,89.0,10.245780,18.435053,3.0,0.0,130.0,16.70,0.0
2,1566083,Ho Chi Minh City,2020-01-01 02:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,1013.50275,88.0,10.245780,18.435053,3.0,0.0,145.0,16.10,0.0
3,1566083,Ho Chi Minh City,2020-01-01 03:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,1012.90130,52.0,10.931203,17.241547,2.0,0.0,175.0,16.45,0.0
4,1566083,Ho Chi Minh City,2020-01-01 04:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,1012.70056,82.0,10.966713,23.198618,3.0,0.0,190.0,17.00,0.0

In [9]:
df.dropna(inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 246640 entries, 226423 to 517679
Data columns (total 30 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   location_id              246640 non-null  int64
 1   location_name            246640 non-null  object
 2   date                     246640 non-null  object
 3   pm10                     246640 non-null  float64
 4   pm2_5                    246640 non-null  float64
 5   carbon_monoxide          246640 non-null  float64
 6   sulphur_dioxide          246640 non-null  float64
 7   ozone                    246640 non-null  float64
 8   nitrogen_dioxide         246640 non-null  float64
 9   aerosol_optical_depth    246640 non-null  float64
 10  dust                     246640 non-null  float64
 11  us_aqi_pm2_5             246640 non-null  float64
 12  us_aqi_pm10              246640 non-null  float64
 13  us_aqi_nitrogen_dioxide  246640 non-null  float64
 14  us_aqi_carbon_monoxide   246640 non-null  float64
 15  us_aqi_ozone             246640 non-null  float64
 16  us_aqi_sulphur_dioxide   246640 non-null  float64
 17  us_aqi                   246640 non-null  float64
 18  temperature_2m           246640 non-null  float64
 19  relative_humidity_2m     246640 non-null  float64
 20  rain                     246640 non-null  float64
 21  surface_pressure         246640 non-null  float64
 22  cloud_cover              246640 non-null  float64
 23  wind_speed_10m           246640 non-null  float64
 24  wind_direction_10m       246640 non-null  float64
 25  weather_code             246640 non-null  float64
 26  sunshine_duration        246640 non-null  float64
 27  boundary_layer_height    246640 non-null  float64
 28  dew_point_2m             246640 non-null  float64
 29  is_day                   246640 non-null  float64
dtypes: float64(27), int64(1), object(2)
memory usage: 58.3+ MB

In [10]:
df.to_csv(
    "../data/clean/data.csv",
    index=False,
)